Dense Layer with multiple layers 

In [9]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()




class DenseLayer:
    def __init__(self, n_inputs, n_neurons):
        self.weights= 0.01*np.random.randn(n_inputs,n_neurons)
        self.biases= np.zeros((1,n_neurons))
    
    def forward(self,inputs):
        self.output=np.dot(inputs,self.weights) + self.biases
        return self.output

X,y= spiral_data(samples=100, classes=3)


layer1=DenseLayer(2,3)
lf1=layer1.forward(X)


layer2= DenseLayer(3,2)
layer2.forward(lf1)

print(layer2.output[:5])

        


[[0.0000000e+00 0.0000000e+00]
 [2.2523950e-06 7.1173298e-07]
 [5.9753474e-06 2.2488973e-06]
 [9.3576182e-06 4.2385718e-06]
 [1.2772904e-05 5.6683862e-06]]


ReLu Activation function
. As we can see all the negative values in the array was set zero and only kept the positve value


In [13]:
import numpy as np
inputs= [0,2,-1,3.3,-2.7,1.1,2.2,-100]
output= np.maximum(0,inputs)
print(output)

[0.  2.  0.  3.3 0.  1.1 2.2 0. ]


In [17]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()




class DenseLayer:
    def __init__(self, n_inputs, n_neurons):
        self.weights= 0.01*np.random.randn(n_inputs,n_neurons)
        self.biases= np.zeros((1,n_neurons))
    
    def forward(self,inputs):
        self.output=np.dot(inputs,self.weights) + self.biases
        return self.output
    
    def forward_activation(self,inputs):
        self.active_relu= np.maximum(0,inputs)
        return self.active_relu

X,y= spiral_data(samples=100, classes=3)


layer1=DenseLayer(2,3)
lf1=layer1.forward(X)
l1_final=layer1.forward_activation(lf1)

layer2= DenseLayer(3,2)
lf2= layer2.forward(lf1)
l2_final= layer2.forward_activation(lf2)

print(l2_final[:5])





# layer2= DenseLayer(3,2)
# layer2.forward(lf1)

# print(layer2.output[:5])

        


[[0.0000000e+00 0.0000000e+00]
 [2.2523950e-06 7.1173298e-07]
 [5.9753474e-06 2.2488973e-06]
 [9.3576182e-06 4.2385718e-06]
 [1.2772904e-05 5.6683862e-06]]


Softmax

In [23]:
inputs= [[1,2,3,2.5],
         [2., 5.,-1., 2],
         [-1.5, 2.7,3.3,-0.8]]

exp_values= np.exp(inputs- np.max(inputs, axis=1, keepdims=True))

probabilities= exp_values/ np.sum(exp_values, axis=1, keepdims=True)
print(probabilities)
print(np.sum(probabilities, axis=1))

[[0.06414769 0.17437149 0.47399085 0.28748998]
 [0.04517666 0.90739747 0.00224921 0.04517666]
 [0.00522984 0.34875873 0.63547983 0.0105316 ]]
[1. 1. 1.]


Implementing Softmax for the classification problem

In [29]:
inputs= [[1,2,3,2.5],
         [2., 5.,-1., 2],
         [-1.5, 2.7,3.3,-0.8]]

class Softmax:

    def activation_softmax(self,inputs):
        exp_values= np.exp(inputs- np.max(inputs, axis=1, keepdims=True))
        probabilities=  exp_values/np.sum(exp_values, axis=1, keepdims=True)
        return probabilities

sf_act=Softmax()
sf_act.activation_softmax(inputs)


[[0.06414769 0.17437149 0.47399085 0.28748998]
 [0.04517666 0.90739747 0.00224921 0.04517666]
 [0.00522984 0.34875873 0.63547983 0.0105316 ]]


Lets Implement the classification neural networkk from scrath

In [37]:
X,y= spiral_data(samples=100, classes=3)
sf_act=Softmax()


layer1=DenseLayer(2,3)
lf1=layer1.forward(X)
l1_final=layer1.forward_activation(lf1)

layer2= DenseLayer(3,2)
lf2= layer2.forward(lf1)
l2_final= layer2.forward_activation(lf2)

layer3= DenseLayer(2,3)
lf3= layer3.forward(lf2)
ff=sf_act.activation_softmax(lf3)


      







[[0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.3333333  0.33333334 0.33333334]
 [0.3333333  0.33333334 0.33333334]
 [0.3333333  0.33333334 0.33333337]
 [0.3333333  0.33333334 0.33333337]
 [0.3333333  0.33333334 0.33333337]
 [0.3333333  0.33333334 0.33333337]
 [0.33333328 0.33333337 0.33333337]
 [0.33333325 0.33333337 0.33333337]
 [0.33333328 0.33333337 0.33333337]
 [0.33333325 0.33333334 0.33333337]
 [0.33333328 0.33333337 0.33333337]
 [0.33333325 0.33333337 0.33333337]
 [0.33333322 0.33333334 0.33333337]
 [0.33333322 0.33333334 0.33333337]
 [0.33333322 0.33333334 0.33333337]
 [0.33333322 0.33333337 0.3333334 ]
 [0.33333325 0.33333334 0.33333337]
 [0.3333332  0.33333334 0.33333343]
 [0.33333325 0.33333334 0.33333343]
 [0.33333325 0.33333337 0.33333337]
 [0.33333325 0.33333334 0.33333337]
 [0.33333322 0.33333337 0.3333334 ]
 [0.33333334 0.3333333  0.3333333 ]
 [0.3333332  0.33333337 0.33333346]
 [0.33333322 0.33333334 0.33333337]
 [0.33333325 0.33333334 0.33